name: LobbyArena
version: '${version}'
main: me.rockyers.lobbyarena.LobbyArena
api-version: '1.18'
load: STARTUP
softdepend: [PlaceholderAPI]
authors: [SkyGameZ, Rockyers]
description: A basic, easy to use, lobby arena plugin
